/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Tela;

import com.mycompany.DAO.ConnectionFactory;
import java.awt.Color;
import java.awt.FontFormatException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author 824144932
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        txtNomeCompleto.setBackground(new Color(0,0,0,1));
        txtNomeExibicao.setBackground(new Color(0,0,0,1));
        txtSenha.setBackground(new Color(0,0,0,1));
        txtConfirmarSenha.setBackground(new Color(0,0,0,1));
        txtEmail.setBackground(new Color(0,0,0,1));
        txtAniversario.setBackground(new Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        txtNomeExibicao = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtAniversario = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(805, 409));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        txtNomeCompleto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeCompleto.setBorder(null);
        txtNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCompletoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeCompleto);
        txtNomeCompleto.setBounds(120, 210, 230, 30);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(120, 280, 230, 30);

        txtConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtConfirmarSenha.setBorder(null);
        getContentPane().add(txtConfirmarSenha);
        txtConfirmarSenha.setBounds(470, 360, 220, 30);

        txtNomeExibicao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeExibicao.setBorder(null);
        txtNomeExibicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeExibicaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeExibicao);
        txtNomeExibicao.setBounds(470, 210, 220, 30);

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSenha.setBorder(null);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(470, 280, 220, 30);

        txtAniversario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAniversario.setBorder(null);
        txtAniversario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAniversarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtAniversario);
        txtAniversario.setBounds(120, 360, 230, 30);

        btCadastrar.setBorder(null);
        btCadastrar.setContentAreaFilled(false);
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrar);
        btCadastrar.setBounds(340, 470, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\gutinho\\Downloads\\WhatsApp Image 2024-11-25 at 21.26.01.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        setSize(new java.awt.Dimension(816, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCompletoActionPerformed
        // TODO add your handling code here:
        txtNomeCompleto.setOpaque(false);
        txtNomeCompleto.setBackground(new Color(0, 0, 0, 0));
        txtNomeCompleto.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_txtNomeCompletoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNomeExibicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeExibicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeExibicaoActionPerformed

    private void txtAniversarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAniversarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAniversarioActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        String nomeCompleto = txtNomeCompleto.getText();
        String nomeExibicao = txtNomeExibicao.getText();
        String senha = txtSenha.getText();
        String confirmarSenha = txtConfirmarSenha.getText();
        String email = txtEmail.getText();
        String aniversario = txtAniversario.getText();
        
        String sql = "INSERT INTO tb_usuario (nomecompleto, nomeexibicao, senha, email, aniversario) VALUES ( ? , ? , ? , ? , ? )";
        if (nomeCompleto.isEmpty() || nomeExibicao.isEmpty() || senha.isEmpty() || email.isEmpty() || aniversario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!");
            return;
        }
        
        if (!senha.equals(confirmarSenha)) {
            System.out.println(senha + " " + confirmarSenha);
            JOptionPane.showMessageDialog(null, "Senhas diferentes! Por favor, insira a mesma senha nos campos 'senha' e 'confirmar senha'!");
            return;
        }
        
        ConnectionFactory cf = new ConnectionFactory();
        try (Connection conn = cf.obtemConexao();
            PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, nomeCompleto);
            ps.setString(2, nomeExibicao);
            ps.setString(3, senha);
            ps.setString(4, email);
            ps.setString(5, aniversario);
            int contInsert = ps.executeUpdate();
            if (contInsert > 0) {
                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
                TelaLogin tLogin = new TelaLogin();
                tLogin.setVisible(true);
                this.dispose();
            }
         } catch (SQLException ex) {
             ex.printStackTrace();
        } catch (FontFormatException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            this.dispose();
            new TelaLogin().setVisible(true);
        } catch (FontFormatException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAniversario;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JTextField txtNomeExibicao;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
