/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Tela;

/**
 *
 * @author 824144932
 */
public class TelaCriarGrupo extends javax.swing.JFrame {

    private String selecao;

    /**
     * Creates new form TelaCriarGrupo
     */
    public TelaCriarGrupo() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeGrupo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboboxTemaGrupo = new javax.swing.JComboBox<>();
        txtTemaGrupo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSenhaGrupo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btEnviarArquivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        txtNomeGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeGrupo);
        txtNomeGrupo.setBounds(80, 80, 255, 22);

        jLabel1.setText("Nome do grupo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 60, 85, 16);

        jLabel2.setText("Tema do grupo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 130, 81, 16);

        comboboxTemaGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tema", "Matemática", "Física", "Biologia", "Português", "Outro" }));
        comboboxTemaGrupo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxTemaGrupoItemStateChanged(evt);
            }
        });
        comboboxTemaGrupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboboxTemaGrupoFocusLost(evt);
            }
        });
        comboboxTemaGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboboxTemaGrupoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboboxTemaGrupoMouseReleased(evt);
            }
        });
        comboboxTemaGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxTemaGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxTemaGrupo);
        comboboxTemaGrupo.setBounds(80, 160, 124, 22);

        txtTemaGrupo.setVisible(false);
        txtTemaGrupo.setToolTipText("");
        txtTemaGrupo.setName(""); // NOI18N
        txtTemaGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemaGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTemaGrupo);
        txtTemaGrupo.setBounds(220, 160, 113, 22);
        txtTemaGrupo.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jLabel3);
        jLabel3.setBounds(355, 85, 0, 0);

        jLabel4.setText("Senha do grupo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 200, 84, 16);

        txtSenhaGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenhaGrupo);
        txtSenhaGrupo.setBounds(80, 220, 139, 22);

        jLabel5.setText("foto do grupo (imagem)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(595, 56, 129, 16);

        btEnviarArquivo.setText("Enviar arquivo");
        btEnviarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarArquivoActionPerformed(evt);
            }
        });
        getContentPane().add(btEnviarArquivo);
        btEnviarArquivo.setBounds(595, 78, 105, 23);

        setSize(new java.awt.Dimension(816, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeGrupoActionPerformed

    private void comboboxTemaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxTemaGrupoActionPerformed
        // TODO add your handling code here:
        int posicao = comboboxTemaGrupo.getSelectedIndex();
        if (posicao == 5)
            txtTemaGrupo.setVisible(true);
        else
            txtTemaGrupo.setVisible(false);
        
        comboboxTemaGrupo.revalidate();
        comboboxTemaGrupo.repaint();
    }//GEN-LAST:event_comboboxTemaGrupoActionPerformed

    private void txtSenhaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaGrupoActionPerformed

    private void comboboxTemaGrupoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboboxTemaGrupoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxTemaGrupoFocusLost

    private void comboboxTemaGrupoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboboxTemaGrupoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxTemaGrupoMouseReleased

    private void comboboxTemaGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboboxTemaGrupoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxTemaGrupoMouseClicked

    private void comboboxTemaGrupoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxTemaGrupoItemStateChanged
        // TODO add your handling code here:
         
    }//GEN-LAST:event_comboboxTemaGrupoItemStateChanged

    private void txtTemaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemaGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemaGrupoActionPerformed

    private void btEnviarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarArquivoActionPerformed
        // TODO add your handling code here:
        TelaFotoGrupo tFotoGrupo = new TelaFotoGrupo();
        tFotoGrupo.setVisible(true);
    }//GEN-LAST:event_btEnviarArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviarArquivo;
    private javax.swing.JComboBox<String> comboboxTemaGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtNomeGrupo;
    private javax.swing.JTextField txtSenhaGrupo;
    private javax.swing.JTextField txtTemaGrupo;
    // End of variables declaration//GEN-END:variables
}
